[package]
name = "examples"
description = "Example models implemented using Teenygrad"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
error-chain = "0.12.4"
itertools = "0.11.0"
log = "0.4.19"

[[bin]]
name = "bert"
path = "src/bert.rs"
